#!/usr/bin/env python

from __future__ import annotations

import os
import re
import sys
from pathlib import Path
from shlex import quote
from subprocess import run

NIX_CONF = """\
# This is based on the nix.conf file generated by https://github.com/DeterminateSystems/nix-installer.

use-xdg-base-directories = true
experimental-features = nix-command flakes
auto-optimise-store = true
always-allow-substitutes = true
bash-prompt-prefix = (nix:$name)\\040
max-jobs = auto
extra-nix-path = nixpkgs=flake:nixpkgs
upgrade-nix-store-path-url = https://install.determinate.systems/nix-upgrade/stable/universal
"""


# pylint: disable=redefined-builtin
def sh(args: list[str | Path], input: bytes | None = None, env: dict[str, str | Path] | None = None) -> None:
    print(' '.join(quote(str(arg)) for arg in args) + (' < INPUT' if input else ''), file=sys.stderr)
    run(args, check=True, input=input, env=env)


def bwrap(outdir: Path, args: list[str | Path], input: bytes | None = None) -> None:
    """
    Use bwrap to run the command with /nix binded to nix_dir.
    This is what the nixsa executable does, but without extra stuff.
    """
    nix_dir = str(outdir / 'nix')
    args1 = (
        ['bwrap', '--bind', nix_dir, '/nix', '--proc', '/proc', '--dev', '/dev', '--bind', '/tmp', '/tmp']
        + ['--bind', str(outdir), str(outdir)]
        + args
    )
    extra_env = {
        'NIX_USER_CONF_FILES': outdir / 'config/nix.conf',
        'NIX_CACHE_HOME': outdir / 'cache',
        'NIX_CONFIG_HOME': outdir / 'config',
        'NIX_DATA_HOME': outdir / 'share',
        'NIX_STATE_HOME': outdir / 'state',
    }
    env = os.environ | extra_env
    sh(args1, input, env=env)


def nixsa_build(nix_archive: Path, nixsa_src: Path, outdir: Path) -> None:
    if not nix_archive.exists():
        raise RuntimeError(f"{nix_archive} doesn't exist")
    if outdir.exists():
        raise RuntimeError(f'{outdir} must not exist before the call')
    outdir = outdir.absolute()
    outdir.mkdir()

    sh(['tar', '-C', outdir, '-xf', nix_archive])
    children = list(outdir.iterdir())
    if len(children) != 1:
        raise RuntimeError('Expecting one main directory in archive')
    (extracted,) = children
    assert extracted.is_dir()
    outdir.joinpath('nix').mkdir()
    extracted.joinpath('store').rename(outdir / 'nix/store')
    install_script = extracted.joinpath('install').read_text()
    reginfo = extracted.joinpath('.reginfo').read_bytes()
    for p in extracted.iterdir():
        p.unlink()
    extracted.rmdir()

    nix_dir = outdir / 'nix'
    nix_dir.joinpath('var').mkdir()
    nix_dir.joinpath('var/nix').mkdir()
    (nix_inst,) = re.findall(r'nix="([^"]+)"', install_script)
    (cacert,) = re.findall(r'cacert="([^"]+)"', install_script)
    bin_dir = outdir / 'bin'
    bin_dir.mkdir()
    nixsa = bin_dir / 'nixsa'
    nixsa_s = nixsa_src.read_bytes()
    nixsa.write_bytes(nixsa_s)
    nixsa.chmod(0o555)

    # Create user directories
    state_dir = outdir / 'state'
    state_dir.mkdir()
    config_dir = outdir / 'config'
    config_dir.mkdir()
    config_dir.joinpath('nix.conf').write_text(NIX_CONF)
    data_dir = outdir / 'share'
    data_dir.mkdir()
    cache_dir = outdir / 'cache'
    cache_dir.mkdir()

    # Create the profile symlink (by default it will be an absolute path, we don't want that)
    state_dir.joinpath('profile').symlink_to('profiles/profile')

    # Initialize the nix DB
    bwrap(outdir, [f'{nix_inst}/bin/nix-store', '--load-db'], input=reginfo)

    # We use `nix-env -i` instead of `nix profile install`, since `nix profile` can seamlessly
    # migrate from nix-env, and not the other way round, so users will be free to choose whatever they prefer.

    # Install the `nix` package
    bwrap(outdir, [f'{nix_inst}/bin/nix-env', '-i', nix_inst])

    # Install an SSL certificate bundle.
    # We now use nixsa, so symlinks will be created.
    sh([outdir / 'bin/nixsa', '-v', f'{nix_inst}/bin/nix-env', '-i', cacert])


def main() -> None:
    from argparse import ArgumentParser

    parser = ArgumentParser(description='build the nixsa directory')
    parser.add_argument('nix_archive', type=Path, help='path to nix installer archive (.tar.xz)')
    parser.add_argument('nixsa_src', type=Path, help='path to the nixsa executable')
    parser.add_argument('outdir', type=Path)
    args = parser.parse_args()

    nixsa_build(args.nix_archive, args.nixsa_src, args.outdir)


if __name__ == '__main__':
    main()
