name: Build x86_64 Linux

on:
  workflow_call:
    inputs:
      cache-key:
        type: string
        required: false
        default: x86_64-linux-artifacts-${{ github.sha }}

jobs:
  build-x86_64-linux:
    name: Build x86_64 Linux
    runs-on: ubuntu-latest
    concurrency: ${{ inputs.cache-key }}
    permissions:
      id-token: "write"
      contents: "read"
    steps:
      - uses: actions/checkout@v4
      - name: Install Nix
        uses: DeterminateSystems/nix-installer-action@main
        with:
          flakehub: true
      - uses: DeterminateSystems/magic-nix-cache-action@main
        with:
          use-gha-cache: false
      - name: Setup tmate session
        uses: mxschmitt/action-tmate@v3
      - name: Build the tarball
        run: |
          nix build .#packages.x86_64-linux.nixsa-tarball -L
          cp result/nixsa-*.tar.xz .
      - name: Create GitHub cache from build artifacts
        uses: actions/cache/save@v4
        with:
          path: nixsa-*.tar.xz
          key: ${{ inputs.cache-key }}
