name: CI

on:
  pull_request:
  push:
    branches: [main, master]

permissions:
  id-token: "write"
  contents: "read"

jobs:

  # build-aarch64-linux:
  #   uses: ./.github/workflows/build-aarch64-linux.yml


  run-x86_64-linux:
    name: Run x86_64 Linux
    runs-on: ubuntu-latest
    permissions:
      id-token: "write"
      contents: "read"
    steps:
      - uses: actions/checkout@v3
      - name: Restore Github cache artifacts
        uses: actions/cache/restore@v3
        with:
          path: nixsa.tar.xz
          key: x86_64-linux-artifacts-b329ab448f3f377aec7ec37f4b79ca4c087d1241
      # - name: Setup tmate session
      #   uses: mxschmitt/action-tmate@v3
      - name: Install bubblewrap
        run: sudo apt-get -y install bubblewrap
      - name: Check tarball
        run: nixsa-build/check_tarball.py nixsa.tar.xz


  # run-aarch64-linux:
  #   name: Run aarch64 Linux
  #   runs-on: namespace-profile-default-arm64
  #   needs: [lints, build-aarch64-linux]
  #   permissions:
  #     id-token: "write"
  #     contents: "read"
  #   steps:
  #     - uses: actions/checkout@v3
  #     - name: Restore Github cache artifacts
  #       uses: actions/cache/restore@v3
  #       with:
  #         path: nixsa.tar.xz
  #         key: aarch64-linux-artifacts-${{ github.sha }}
  #     - name: Check tarball
  #       run: nixsa-build/check_tarball.py nixsa.tar.xz
  